config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'

  devise_for :users

  resources :profiles, only: [:new, :create, :edit, :update]
  resources :products
  resources :cart

  resources :product do
    resources :orders
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  has_many :orders
  has_many :products ,through: :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :cart ,dependent: :destroy
  belongs_to :product ,dependent: :destroy
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :carts, through: :orders

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_one :cart

  def has_profile?
    profile.present? && profile.persisted?
  end

  def full_name
    profile.full_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_user!

  def create
    @cart = current_user.carts.create(cart_params)
  end

  private

  def cart_params
    params.require(:cart).permits(:product_id, :total_price)

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_action :authenticate_user
before_action :find_cart, only: [:create]

  def create
    @order = Order.create(order_params)
  end

private

  def select_product
    @product = Product.find(params[:product_id])
  end

  def find_cart
    @cart = current_user.cart
  end

  def order_params
     params.require(:order).permit(:product_id,:quantity,:cart_id)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile updated"
    else
      render :edit
    end
  end

  private

  def set_profile
    @profile = current_user.profile
  end

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :address, :telephone)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaizon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <% if notice %>
        <p class="alert alert-info"><%= notice %></p>
      <% elsif alert %>
        <p class="alert alert-danger"><%= alert%></p>
      <% end %>
    <div class="container">
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/products/index.html.erb
<main>
  <h1> Products </h1>
  <div id="flex_wrapper">
    <% @products.each do |product| %>
    <article>
      <h1><%= link_to product.name, product_path(product.id)%></h1>
      <%= link_to image_tag(product.image), product_path(product.id)%>
    </article>
    <% end %>
  </div>
</main>

app/views/products/show.html.erb
<main>
  <h1><%= @product.name %></h1>

  <%= image_tag @product.image %>
  <p><%= @product.description %></p>
  <p><%= @product.price %></p>
</main>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <%= render "profiles/validation_errors" %>
  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Address</label>
    <%= f.text_area :address, rows: 2, placeholder: "Address", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :telephone, placeholder: "telephone", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/profiles/_validation_errors.html.erb
<% @profile.errors.full_messages.each do |msg| %>
  <p class="alert alert-danger"><%= msg %></p>
<% end %>

app/views/profiles/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Edit your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Create your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaizon", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.has_profile? ? current_user.full_name : current_user.email  %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <% if current_user.has_profile? %>
                <li><%= link_to "Edit Profile", edit_profile_path(current_user.profile) %></li>
              <% else %>
                <li><%= link_to "Create Profile", new_profile_path %></li>
              <% end %>
              <li><%= link_to "Edit Password", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Cart" %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>